name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PWD }} && \
          docker build -t ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }} . && \
          docker push ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd scripts
            sudo docker ps -a -q --filter "name=streaming" | grep -q . && docker stop streaming && docker rm streaming | true
            sudo docker rmi ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}
            sudo docker pull ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}
            docker run -d -p 8080:8080 --env-file=env_list.txt --name streaming ${{ secrets.DOCKER_ID }}/${{ secrets.DOCKER_REPO }}
            docker rmi -f $(docker images -f "dangling=true" -q) || true